# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcdb0ea629b99de55b629f3cee87a8fa7949a70ca99ca141b3e3c66897afc706e519542283ff77a2ec18d6537f2ed56fc6710488df6b4ec04e0393ef1d66cfce

test:
  secret_key_base: 44a17d19a2ed052d97b0c62f71455afb231ecac04c9025bf10d10501032e529c233d389efa167343e7e9300a7250eefef12fe8480cec4cde8b81ab8de322a9d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
